Add energy thermostat api
lost-carrier/netatmo-api pull request #3
Opened 2018-12-30 22:11 UTC by robmelfi

Homesdata retrieve user's homes and their topology  
Endpoint: https://api.netatmo.com/api/homesdata  
Referece: https://dev.netatmo.com/en-US/resources/technical/reference/energy/homesdata

Homestatus get the current status and data measured for all home devices  
Endpoint: https://api.netatmo.com/api/homestatus  
Reference: https://dev.netatmo.com/en-US/resources/technical/reference/energy/homestatus

2019-01-08 17:16 UTC, lost-carrier commented
sry for the delay - was on vacation...

2019-01-15 10:58 UTC, lost-carrier requested changes
Could you add a small test in NetatmoHttpClientTest? (...afaik I cannot even see the response format  if I don't own such a thermostat, right?)

2019-01-15 10:58 UTC, lost-carrier commented on pom.xml
> +		<java-version>1.8</java-version>
As far as I can see there is not features of 1.8 used so I would leave it at 1.7 for better backward compatibility.
```suggestion
		<java-version>1.7</java-version>
```

2019-01-15 10:58 UTC, lost-carrier commented on pom.xml
> +        <dependency>
Hmm... not used? ...should be removed?

2019-01-15 13:14 UTC, robmelfi commented on pom.xml
> +        <dependency>
yes

2019-01-15 14:29 UTC, robmelfi commented
@lost-carrier I added the tests 👍🏼

2019-01-15 17:49 UTC, lost-carrier commented
@robmelfi awesome - thanks!

2019-01-15 17:49 UTC, merged